# Generated by Django 5.0.7 on 2024-08-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parents_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
