# Generated by Django 5.1 on 2024-08-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsManager', '0002_alter_student_parents_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_fees',
            field=models.BooleanField(default=False),
        ),
    ]
