# Generated by Django 5.1 on 2024-08-13 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentsManager', '0003_student_student_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='busFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('due_date', models.DateField()),
                ('last_Paid', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsManager.student')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('due_date', models.DateField()),
                ('fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsManager.student')),
            ],
        ),
    ]
