# Generated by Django 5.1 on 2024-08-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='bus_fees',
            field=models.BooleanField(default=False),
        ),
    ]
