# Generated by Django 5.1 on 2024-08-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsManager', '0002_fee_bus_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='busfees',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busfees',
            name='bus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
