# Generated by Django 5.1 on 2024-08-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsManager', '0003_busfees_total_fees_alter_busfees_bus_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busfees',
            name='bus_amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
